apiVersion: apps/v1
kind: Deployment
metadata:
  name: upcommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upcommerce-app
  template:
    metadata:
      labels:
        app: upcommerce-app
    spec:
      containers:
      - name: upcommerce
        image: 626205068/upcommerce:v3
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: upcommerce-app-service
spec:
  type: NodePort
  ports:
  - port: 5001
    targetPort: 5000
    # nodePort: 30001
  selector:
    app: upcommerce-app
